exports.run = function(client, message, args) {

    message.channel.sendMessage('HIT THE DUN DUN FLOOOAAAAAAARRRRRRRHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH');
}
